import { Station } from '../types/database'

export const mockStations: Omit<Station, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    name: 'Tata Power Charging Station - Connaught Place',
    address: 'Block A, Connaught Place',
    city: 'New Delhi',
    pincode: '110001',
    latitude: 28.6304,
    longitude: 77.2177,
    operator: 'Tata Power',
    connectors: [
      { type: 'CCS2', power_rating: 50, available_ports: 2, total_ports: 4 },
      { type: 'Type2', power_rating: 22, available_ports: 1, total_ports: 2 },
    ],
    charger_types: ['DC', 'Fast'],
    facilities: ['Parking', 'Café', 'WiFi'],
    price_per_kwh: 8.5,
    availability_status: 'Available',
  },
  {
    name: 'Zeon Charging Hub - Bandra',
    address: 'Hill Road, Bandra West',
    city: 'Mumbai',
    pincode: '400050',
    latitude: 19.0596,
    longitude: 72.8295,
    operator: 'Zeon',
    connectors: [
      { type: 'CCS2', power_rating: 150, available_ports: 1, total_ports: 2 },
      { type: 'CHAdeMO', power_rating: 50, available_ports: 0, total_ports: 1 },
    ],
    charger_types: ['DC', 'Ultra-Fast'],
    facilities: ['Parking', 'Restrooms', 'WiFi'],
    price_per_kwh: 12.0,
    availability_status: 'Busy',
  },
  {
    name: 'Statiq Charging Point - Koramangala',
    address: '5th Block, Koramangala',
    city: 'Bangalore',
    pincode: '560095',
    latitude: 12.9352,
    longitude: 77.6245,
    operator: 'Statiq',
    connectors: [
      { type: 'Type2', power_rating: 22, available_ports: 3, total_ports: 4 },
      { type: 'CCS2', power_rating: 50, available_ports: 1, total_ports: 2 },
    ],
    charger_types: ['AC', 'DC'],
    facilities: ['Parking', 'Café', 'Restrooms', 'WiFi'],
    price_per_kwh: 9.0,
    availability_status: 'Available',
  },
  {
    name: 'Tata Power EV Station - Salt Lake',
    address: 'Sector V, Salt Lake',
    city: 'Kolkata',
    pincode: '700091',
    latitude: 22.5726,
    longitude: 88.3639,
    operator: 'Tata Power',
    connectors: [
      { type: 'CCS2', power_rating: 50, available_ports: 0, total_ports: 2 },
      { type: 'Type2', power_rating: 22, available_ports: 2, total_ports: 3 },
    ],
    charger_types: ['AC', 'DC'],
    facilities: ['Parking', 'WiFi'],
    price_per_kwh: 8.0,
    availability_status: 'Offline',
  },
  {
    name: 'Zeon Fast Charging - Hitech City',
    address: 'Hitech City Main Road',
    city: 'Hyderabad',
    pincode: '500081',
    latitude: 17.4486,
    longitude: 78.3908,
    operator: 'Zeon',
    connectors: [
      { type: 'CCS2', power_rating: 150, available_ports: 2, total_ports: 3 },
      { type: 'GB/T', power_rating: 60, available_ports: 1, total_ports: 2 },
    ],
    charger_types: ['DC', 'Ultra-Fast'],
    facilities: ['Parking', 'Café', 'Restrooms', 'WiFi'],
    price_per_kwh: 11.5,
    availability_status: 'Available',
  },
  {
    name: 'Statiq Charging Hub - Baner',
    address: 'Baner Road, Baner',
    city: 'Pune',
    pincode: '411045',
    latitude: 18.5596,
    longitude: 73.7864,
    operator: 'Statiq',
    connectors: [
      { type: 'Type2', power_rating: 22, available_ports: 2, total_ports: 4 },
      { type: 'CCS2', power_rating: 50, available_ports: 1, total_ports: 2 },
    ],
    charger_types: ['AC', 'DC'],
    facilities: ['Parking', 'Restrooms'],
    price_per_kwh: 9.5,
    availability_status: 'Available',
  },
  {
    name: 'Tata Power Station - Adyar',
    address: 'Adyar Main Road',
    city: 'Chennai',
    pincode: '600020',
    latitude: 13.0067,
    longitude: 80.2206,
    operator: 'Tata Power',
    connectors: [
      { type: 'CCS2', power_rating: 50, available_ports: 1, total_ports: 3 },
      { type: 'CHAdeMO', power_rating: 50, available_ports: 0, total_ports: 1 },
    ],
    charger_types: ['DC', 'Fast'],
    facilities: ['Parking', 'Café', 'WiFi'],
    price_per_kwh: 8.5,
    availability_status: 'Busy',
  },
  {
    name: 'Zeon Ultra-Fast Charging - Gurgaon',
    address: 'DLF Cyber City, Gurgaon',
    city: 'Gurgaon',
    pincode: '122002',
    latitude: 28.4962,
    longitude: 77.0940,
    operator: 'Zeon',
    connectors: [
      { type: 'CCS2', power_rating: 150, available_ports: 2, total_ports: 4 },
      { type: 'Type2', power_rating: 22, available_ports: 1, total_ports: 2 },
    ],
    charger_types: ['DC', 'Ultra-Fast'],
    facilities: ['Parking', 'Café', 'Restrooms', 'WiFi'],
    price_per_kwh: 13.0,
    availability_status: 'Available',
  },
  {
    name: 'Statiq Charging Point - Sector 18',
    address: 'Sector 18, Noida',
    city: 'Noida',
    pincode: '201301',
    latitude: 28.5937,
    longitude: 77.3214,
    operator: 'Statiq',
    connectors: [
      { type: 'Type2', power_rating: 22, available_ports: 3, total_ports: 4 },
      { type: 'CCS2', power_rating: 50, available_ports: 0, total_ports: 2 },
    ],
    charger_types: ['AC', 'DC'],
    facilities: ['Parking', 'WiFi'],
    price_per_kwh: 9.0,
    availability_status: 'Available',
  },
  {
    name: 'Tata Power EV Hub - Whitefield',
    address: 'Whitefield Main Road',
    city: 'Bangalore',
    pincode: '560066',
    latitude: 12.9698,
    longitude: 77.7499,
    operator: 'Tata Power',
    connectors: [
      { type: 'CCS2', power_rating: 50, available_ports: 2, total_ports: 3 },
      { type: 'Type2', power_rating: 22, available_ports: 2, total_ports: 3 },
    ],
    charger_types: ['AC', 'DC', 'Fast'],
    facilities: ['Parking', 'Café', 'Restrooms', 'WiFi'],
    price_per_kwh: 8.5,
    availability_status: 'Available',
  },
  {
    name: 'Zeon Charging Station - Andheri',
    address: 'Andheri West, SV Road',
    city: 'Mumbai',
    pincode: '400053',
    latitude: 19.1136,
    longitude: 72.8297,
    operator: 'Zeon',
    connectors: [
      { type: 'CCS2', power_rating: 150, available_ports: 1, total_ports: 2 },
      { type: 'CHAdeMO', power_rating: 50, available_ports: 1, total_ports: 1 },
    ],
    charger_types: ['DC', 'Ultra-Fast'],
    facilities: ['Parking', 'Restrooms', 'WiFi'],
    price_per_kwh: 12.0,
    availability_status: 'Busy',
  },
  {
    name: 'Statiq Fast Charging - Vasant Kunj',
    address: 'Vasant Kunj, New Delhi',
    city: 'New Delhi',
    pincode: '110070',
    latitude: 28.5245,
    longitude: 77.1555,
    operator: 'Statiq',
    connectors: [
      { type: 'Type2', power_rating: 22, available_ports: 2, total_ports: 4 },
      { type: 'CCS2', power_rating: 50, available_ports: 2, total_ports: 3 },
    ],
    charger_types: ['AC', 'DC'],
    facilities: ['Parking', 'Café', 'WiFi'],
    price_per_kwh: 9.5,
    availability_status: 'Available',
  },
  {
    name: 'Tata Power Station - Powai',
    address: 'Powai Lake Road',
    city: 'Mumbai',
    pincode: '400076',
    latitude: 19.1176,
    longitude: 72.9067,
    operator: 'Tata Power',
    connectors: [
      { type: 'CCS2', power_rating: 50, available_ports: 1, total_ports: 2 },
      { type: 'Type2', power_rating: 22, available_ports: 1, total_ports: 2 },
    ],
    charger_types: ['AC', 'DC'],
    facilities: ['Parking', 'WiFi'],
    price_per_kwh: 8.5,
    availability_status: 'Available',
  },
  {
    name: 'Zeon Charging Hub - Indiranagar',
    address: '100 Feet Road, Indiranagar',
    city: 'Bangalore',
    pincode: '560038',
    latitude: 12.9784,
    longitude: 77.6408,
    operator: 'Zeon',
    connectors: [
      { type: 'CCS2', power_rating: 150, available_ports: 2, total_ports: 3 },
      { type: 'Type2', power_rating: 22, available_ports: 2, total_ports: 3 },
    ],
    charger_types: ['DC', 'Ultra-Fast'],
    facilities: ['Parking', 'Café', 'Restrooms', 'WiFi'],
    price_per_kwh: 12.5,
    availability_status: 'Available',
  },
  {
    name: 'Statiq Charging Point - Jubilee Hills',
    address: 'Jubilee Hills, Road No. 36',
    city: 'Hyderabad',
    pincode: '500033',
    latitude: 17.4332,
    longitude: 78.4011,
    operator: 'Statiq',
    connectors: [
      { type: 'Type2', power_rating: 22, available_ports: 3, total_ports: 4 },
      { type: 'CCS2', power_rating: 50, available_ports: 1, total_ports: 2 },
    ],
    charger_types: ['AC', 'DC'],
    facilities: ['Parking', 'Restrooms', 'WiFi'],
    price_per_kwh: 9.0,
    availability_status: 'Available',
  },
  {
    name: 'Tata Power EV Station - Sector 29',
    address: 'Sector 29, Gurgaon',
    city: 'Gurgaon',
    pincode: '122001',
    latitude: 28.4595,
    longitude: 77.0266,
    operator: 'Tata Power',
    connectors: [
      { type: 'CCS2', power_rating: 50, available_ports: 0, total_ports: 2 },
      { type: 'Type2', power_rating: 22, available_ports: 1, total_ports: 2 },
    ],
    charger_types: ['AC', 'DC'],
    facilities: ['Parking', 'WiFi'],
    price_per_kwh: 8.5,
    availability_status: 'Offline',
  },
  {
    name: 'Zeon Fast Charging - Wakad',
    address: 'Wakad Main Road',
    city: 'Pune',
    pincode: '411057',
    latitude: 18.5993,
    longitude: 73.7629,
    operator: 'Zeon',
    connectors: [
      { type: 'CCS2', power_rating: 150, available_ports: 1, total_ports: 2 },
      { type: 'GB/T', power_rating: 60, available_ports: 1, total_ports: 1 },
    ],
    charger_types: ['DC', 'Ultra-Fast'],
    facilities: ['Parking', 'Café', 'Restrooms', 'WiFi'],
    price_per_kwh: 11.5,
    availability_status: 'Available',
  },
  {
    name: 'Statiq Charging Hub - T Nagar',
    address: 'Pondy Bazaar, T Nagar',
    city: 'Chennai',
    pincode: '600017',
    latitude: 13.0418,
    longitude: 80.2341,
    operator: 'Statiq',
    connectors: [
      { type: 'Type2', power_rating: 22, available_ports: 2, total_ports: 4 },
      { type: 'CCS2', power_rating: 50, available_ports: 1, total_ports: 2 },
    ],
    charger_types: ['AC', 'DC'],
    facilities: ['Parking', 'Café', 'WiFi'],
    price_per_kwh: 9.0,
    availability_status: 'Available',
  },
  {
    name: 'Tata Power Station - Salt Lake Sector 1',
    address: 'Sector 1, Salt Lake',
    city: 'Kolkata',
    pincode: '700064',
    latitude: 22.5749,
    longitude: 88.4058,
    operator: 'Tata Power',
    connectors: [
      { type: 'CCS2', power_rating: 50, available_ports: 2, total_ports: 3 },
      { type: 'Type2', power_rating: 22, available_ports: 2, total_ports: 3 },
    ],
    charger_types: ['AC', 'DC', 'Fast'],
    facilities: ['Parking', 'Café', 'Restrooms', 'WiFi'],
    price_per_kwh: 8.5,
    availability_status: 'Available',
  },
  {
    name: 'Zeon Ultra-Fast Hub - Connaught Place',
    address: 'Block B, Connaught Place',
    city: 'New Delhi',
    pincode: '110001',
    latitude: 28.6328,
    longitude: 77.2197,
    operator: 'Zeon',
    connectors: [
      { type: 'CCS2', power_rating: 150, available_ports: 3, total_ports: 4 },
      { type: 'Type2', power_rating: 22, available_ports: 2, total_ports: 3 },
    ],
    charger_types: ['DC', 'Ultra-Fast'],
    facilities: ['Parking', 'Café', 'Restrooms', 'WiFi'],
    price_per_kwh: 13.0,
    availability_status: 'Available',
  },
]

